## Introduction to Numpy
* Numerical Python
* Linear Algebra for Python
* Has bindings to C library
* High Performance Scientific Computing

In [1]:
import numpy as np

Numpy ndarray - A multidimensional Array Object
* HOMOGENOUES DATA

In [2]:
lst_data = list(range(1, 11))
print(lst_data)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [3]:
np.array(lst_data)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
e = np.array([lst_data])

In [5]:
print(e.shape)
print(e.ndim)
print(e)

(1, 10)
2
[[ 1  2  3  4  5  6  7  8  9 10]]


In [6]:
np1 = np.array(lst_data)

In [7]:
np1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
print(type(np1))

<class 'numpy.ndarray'>


### Shape

In [9]:
np1.shape

(10,)

In [10]:
np1.ndim

1

### Create a multi-dimensinal array

In [11]:
my_matrix = [[1, 2, 3, 10], [4, 5, 6, 11], [7, 8, 9, 12]]

In [12]:
md_arr = np.array(my_matrix)

In [13]:
md_arr

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [14]:
md_arr.shape

(3, 4)

In [15]:
md_arr.ndim

2

In [26]:
md_arr.dtype

dtype('int32')

In [27]:
i = 10

In [28]:
print(type(i))

<class 'int'>


In [18]:
my_matrix1 = [[[1, 2, 3, 10], [4, 5, 6, 11], [7, 8, 9, 12]], [[11, 12, 13, 100], [14, 15, 16, 111], [17, 18, 19, 112]]]

In [19]:
md_arr1 = np.array(my_matrix1)

In [22]:
print(md_arr1.shape)
print(md_arr1.ndim)

(2, 3, 4)
3


In [23]:
arr1 = np.array([1, 2, 3, 4, 5], dtype=float)

In [24]:
arr1

array([1., 2., 3., 4., 5.])

In [25]:
arr1.dtype

dtype('float64')

In [29]:
lst_odd_size = [[1, 2, 3], [4, 5], [7, 8, 9]]
lst_odd_size

[[1, 2, 3], [4, 5], [7, 8, 9]]

In [30]:
md_arr_odd = np.array(lst_odd_size)

In [31]:
md_arr_odd

array([list([1, 2, 3]), list([4, 5]), list([7, 8, 9])], dtype=object)

In [32]:
md_arr_odd.shape

(3,)

In [33]:
md_arr_odd.ndim

1

In [34]:
md_arr_odd.dtype

dtype('O')

In [35]:
my_list = [1, 2, 3, 4, 5, 6]

In [39]:
arr1 = np.array(my_list, dtype='i')

In [40]:
arr1

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [41]:
arr1.shape

(6,)

In [42]:
arr2 = arr1.reshape(3, 2)

In [43]:
arr2

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [44]:
arr2.ndim

2

In [45]:
arr1

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [49]:
arr3 = arr1.reshape(3, -1)

In [50]:
arr3

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [51]:
arr3.shape

(3, 2)

In [52]:
my_list1 = list(range(1, 6))
my_list2 = list(range(10, 15))
my_list3 = list(range(20, 25))

In [53]:
my_list1, my_list2, my_list3

([1, 2, 3, 4, 5], [10, 11, 12, 13, 14], [20, 21, 22, 23, 24])

In [54]:
mul_arr = np.array([my_list1, my_list2, my_list3])

In [55]:
mul_arr

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [56]:
mul_arr.shape

(3, 5)

In [57]:
mul_arr_15 = mul_arr.reshape(1, 15)

In [58]:
mul_arr_15.shape

(1, 15)

In [59]:
mul_arr_15.ndim

2

In [60]:
mul_arr_51 = mul_arr_15.reshape(15, 1)

In [61]:
mul_arr_51.shape

(15, 1)

In [62]:
mul_arr_51.ndim

2

In [63]:
mul_arr_15

array([[ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24]])

In [64]:
mul_arr_51

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [10],
       [11],
       [12],
       [13],
       [14],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [65]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [66]:
a.ndim

1

In [67]:
a.reshape(6, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [68]:
b = a.reshape(6, 4, 1)

In [69]:
b.ndim

3

In [70]:
b

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15]],

       [[16],
        [17],
        [18],
        [19]],

       [[20],
        [21],
        [22],
        [23]]])

In [71]:
c = a.reshape(3, 2, 4)

In [72]:
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [73]:
x = np.array([1, 2, 3], dtype = np.int8)

In [74]:
print(x.itemsize)

1


In [75]:
x = np.array([1, 2, 3], dtype = np.int64)

In [76]:
print(x.itemsize)

8


In [77]:
x = np.array([1, 2, 3], dtype = np.int32)
print(x.itemsize)

4


In [78]:
arr1 = np.arange(0, 11, 2)

In [79]:
arr1

array([ 0,  2,  4,  6,  8, 10])

In [80]:
arr = np.random.randint(20, 30, 10)

In [81]:
arr

array([27, 27, 23, 23, 21, 24, 20, 29, 26, 24])

In [82]:
len(arr)

10

In [83]:
# index starts with zero
arr[0]

27

In [84]:
arr[5:8]

array([24, 20, 29])

In [85]:
arr[:3]

array([27, 27, 23])

In [86]:
arr[3:]

array([23, 21, 24, 20, 29, 26, 24])

In [87]:
arr[-1]

24

In [ ]:
# Broadcasting
# Array slices are *actually* views on the original array
# That means, data isn't copied, and any modifications to the view would be reflected back to the source array

In [88]:
arr

array([27, 27, 23, 23, 21, 24, 20, 29, 26, 24])

In [89]:
arr[0:5] = 99

In [90]:
arr

array([99, 99, 99, 99, 99, 24, 20, 29, 26, 24])

In [91]:
new_arr = np.random.randint(10, 20, 10)

In [92]:
new_arr

array([16, 18, 13, 17, 19, 19, 13, 15, 17, 12])

In [93]:
slice_new_arr = new_arr[0:5]

In [94]:
slice_new_arr

array([16, 18, 13, 17, 19])

In [95]:
slice_new_arr[0] = 100

In [96]:
slice_new_arr

array([100,  18,  13,  17,  19])

In [97]:
new_arr

array([100,  18,  13,  17,  19,  19,  13,  15,  17,  12])

In [98]:
slice_new_arr[:] = 111

In [99]:
slice_new_arr

array([111, 111, 111, 111, 111])

In [100]:
new_arr

array([111, 111, 111, 111, 111,  19,  13,  15,  17,  12])

In [101]:
new_arr_copy = new_arr.copy()

In [102]:
new_arr

array([111, 111, 111, 111, 111,  19,  13,  15,  17,  12])

In [103]:
new_arr_copy

array([111, 111, 111, 111, 111,  19,  13,  15,  17,  12])

In [104]:
new_arr_copy[0:5] = 123

In [105]:
new_arr_copy

array([123, 123, 123, 123, 123,  19,  13,  15,  17,  12])

In [106]:
new_arr

array([111, 111, 111, 111, 111,  19,  13,  15,  17,  12])

In [107]:
a = list(range(1, 11))

In [108]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [109]:
b = a[0:5]

In [110]:
b

[1, 2, 3, 4, 5]

In [111]:
b[0] = 100

In [112]:
b

[100, 2, 3, 4, 5]

In [113]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [114]:
b[0:3] = 123

TypeError: can only assign an iterable

In [115]:
new_arr = np.random.randint(10, 20, 100)

In [116]:
new_arr

array([17, 13, 13, 10, 12, 14, 12, 13, 19, 19, 13, 15, 11, 14, 10, 15, 13,
       10, 19, 12, 19, 13, 11, 13, 17, 17, 19, 16, 11, 11, 15, 15, 14, 13,
       11, 18, 15, 11, 10, 10, 14, 14, 15, 15, 16, 11, 12, 10, 11, 10, 12,
       12, 13, 18, 17, 12, 15, 15, 18, 14, 10, 18, 17, 11, 14, 16, 15, 18,
       18, 14, 15, 19, 19, 13, 17, 16, 12, 19, 14, 19, 15, 11, 11, 15, 10,
       11, 14, 10, 10, 12, 11, 14, 11, 19, 12, 11, 18, 17, 12, 19])

In [117]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)

In [118]:
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

In [119]:
x

array([[1., 2.],
       [3., 4.]])

In [120]:
y

array([[5., 6.],
       [7., 8.]])

In [121]:
x.ndim, y.ndim

(2, 2)

In [122]:
x + y

array([[ 6.,  8.],
       [10., 12.]])

In [123]:
x - y

array([[-4., -4.],
       [-4., -4.]])

In [124]:
y - x

array([[4., 4.],
       [4., 4.]])

In [125]:
np.add(x, y)

array([[ 6.,  8.],
       [10., 12.]])

In [126]:
np.subtract(x, y)

array([[-4., -4.],
       [-4., -4.]])

In [127]:
np.subtract(y, x)

array([[4., 4.],
       [4., 4.]])

In [128]:
x * y

array([[ 5., 12.],
       [21., 32.]])

In [129]:
x

array([[1., 2.],
       [3., 4.]])

In [130]:
y

array([[5., 6.],
       [7., 8.]])

In [131]:
np.multiply(x, y)

array([[ 5., 12.],
       [21., 32.]])

In [132]:
# dot product

In [133]:
x.dot(y)

array([[19., 22.],
       [43., 50.]])

In [134]:
x, y

(array([[1., 2.],
        [3., 4.]]),
 array([[5., 6.],
        [7., 8.]]))

In [135]:
x / y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [136]:
y / x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [139]:
x

array([[1., 2.],
       [3., 4.]])

In [137]:
print(np.sum(x)) # compute sum of all elements of the array

10.0


In [138]:
print(np.sum(x, axis=0)) # compute sum of each column

[4. 6.]


In [140]:
print(np.sum(x, axis=1)) # compute sum of each row

[3. 7.]


In [141]:
arr = np.arange(15)

In [142]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [143]:
arr = arr.reshape(3, 5)

In [144]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [145]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [146]:
np.max(arr)

14

In [147]:
np.min(arr)

0

In [148]:
x

array([[1., 2.],
       [3., 4.]])

In [149]:
y

array([[5., 6.],
       [7., 8.]])

In [150]:
np.maximum(x, y)

array([[5., 6.],
       [7., 8.]])

In [151]:
a = np.array([[1, 2], [2, 1]], dtype=np.float64)
b = np.array([[2, 1], [1, 2]], dtype=np.float64)

In [152]:
np.maximum(a, b)

array([[2., 2.],
       [2., 2.]])

In [153]:
np.minimum(a, b)

array([[1., 1.],
       [1., 1.]])

In [154]:
a

array([[1., 2.],
       [2., 1.]])

In [155]:
b

array([[2., 1.],
       [1., 2.]])

In [156]:
zeros_a = np.zeros_like(a)

In [157]:
zeros_a

array([[0., 0.],
       [0., 0.]])

In [158]:
ones_a = np.ones_like(a)

In [159]:
ones_a

array([[1., 1.],
       [1., 1.]])

In [160]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [161]:
a

array([[1., 2.],
       [2., 1.]])

In [ ]:
i = 10

In [ ]:
print("Cell 1")

print("Cell 2")

print("Cell 3")

In [ ]:
ones_a

np.zeros((3, 3))

a

In [ ]:
a = np.array([[1, 2], [2, 1]], dtype=np.float64)
b = np.array([[2, 1], [1, 2]], dtype=np.float64)

np.maximum(a, b)

np.minimum(a, b)

a



b

In [162]:
a = np.arange(24)
print(a)

a.ndim


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


1

In [163]:
b = a.reshape(2, 4, 3)
b.ndim

3

In [164]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [167]:
b[0][1][1]

4

In [169]:
b[0,1,1]

4

In [170]:
b[0:1,1:2,1]

array([[4]])

In [ ]:
b[1][1][0]

In [ ]:
for x in range(0, 2):
    for y in range(0, 4):
        for z in range(0, 3):
            print(b[x][y][z])

In [171]:
c = a.reshape(2, 2, 3, 2)

In [172]:
c

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]],


       [[[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]]]])

In [173]:
c.ndim

4

In [ ]:
c[1][0][0][0]